apiVersion: v1
kind: ConfigMap
metadata:
  name: weather-sentinel-config
  namespace: weather-sentinel
data:
  # Configurazioni database
  MYSQL_HOST_SGA: "sga-db-service"
  MYSQL_HOST_SGM: "sgm-db-service"
  MYSQL_HOST_SED: "sed-db-service" 
  MYSQL_HOST_GLS: "gls-db-service"
  MYSQL_PORT: "3306"
  MYSQL_USER: "root"
  
  # Database names
  MYSQL_DATABASE_SGA: "SGA_db"
  MYSQL_DATABASE_SGM: "SGM_db"
  MYSQL_DATABASE_SED: "SED_db"
  MYSQL_DATABASE_GLS: "GLS_db"
  
  # Port exposing
  PORTA_SGA: "50053"
  PORTA_SGM: "50054"
  PORTA_SED: "50055"
  PORTA_GLS: "50056"
  
  # Kafka configuration
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  KAFKA_TOPIC: "weather-alerts"
  
  # Zookeeper configuration
  ZOOKEEPER_CLIENT_PORT: "2181"
  ZOOKEEPER_TICK_TIME: "2000"