# SGA Database
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sga-db-pvc
  namespace: weather-sentinel
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sga-db
  namespace: weather-sentinel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sga-db
  template:
    metadata:
      labels:
        app: sga-db
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: weather-sentinel-secrets
              key: SGA_DB_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: weather-sentinel-config
              key: MYSQL_DATABASE_SGA
        volumeMounts:
        - name: sga-db-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: sga-db-storage
        persistentVolumeClaim:
          claimName: sga-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sga-db-service
  namespace: weather-sentinel
spec:
  selector:
    app: sga-db
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP
---
# SGM Database
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sgm-db-pvc
  namespace: weather-sentinel
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sgm-db
  namespace: weather-sentinel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sgm-db
  template:
    metadata:
      labels:
        app: sgm-db
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: weather-sentinel-secrets
              key: SGM_DB_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: weather-sentinel-config
              key: MYSQL_DATABASE_SGM
        volumeMounts:
        - name: sgm-db-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: sgm-db-storage
        persistentVolumeClaim:
          claimName: sgm-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sgm-db-service
  namespace: weather-sentinel
spec:
  selector:
    app: sgm-db
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP
---
# SED Database
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sed-db-pvc
  namespace: weather-sentinel
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sed-db
  namespace: weather-sentinel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sed-db
  template:
    metadata:
      labels:
        app: sed-db
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: weather-sentinel-secrets
              key: SED_DB_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: weather-sentinel-config
              key: MYSQL_DATABASE_SED
        volumeMounts:
        - name: sed-db-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: sed-db-storage
        persistentVolumeClaim:
          claimName: sed-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sed-db-service
  namespace: weather-sentinel
spec:
  selector:
    app: sed-db
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP
---
# GLS Database
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gls-db-pvc
  namespace: weather-sentinel
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gls-db
  namespace: weather-sentinel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gls-db
  template:
    metadata:
      labels:
        app: gls-db
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: weather-sentinel-secrets
              key: GLS_DB_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: weather-sentinel-config
              key: MYSQL_DATABASE_GLS
        volumeMounts:
        - name: gls-db-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: gls-db-storage
        persistentVolumeClaim:
          claimName: gls-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: gls-db-service
  namespace: weather-sentinel
spec:
  selector:
    app: gls-db
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP