apiVersion: v1
kind: PersistentVolume
metadata:
  name: gls-db-pv
  labels:
    type: local
    app: gls-db
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/gls-db"
  persistentVolumeReclaimPolicy: Delete