apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-data-pv
  labels:
    type: local
    app: kafka-data
spec:
  storageClassName: standard
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/kafka/data"
  persistentVolumeReclaimPolicy: Delete 