apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sed-db-pvc
  namespace: weather-sentinel
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: sed-db