
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sed-db-pv
  labels:
    type: local
    app: sed-db
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/sed-db"
  persistentVolumeReclaimPolicy: Delete