global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/prometheus.rules

scrape_configs:
  - job_name: 'sga'
    scrape_interval: 15s
    metrics_path: /prometheus/metrics
    static_configs:
      - targets: ['api-gateway:80']
    
  - job_name: 'sgm'
    scrape_interval: 15s
    metrics_path: /prometheus/metrics/sgm
    static_configs:
      - targets: ['api-gateway:80']
  
  - job_name: 'sed'
    scrape_interval: 15s
    metrics_path: /prometheus/metrics/sed
    static_configs:
      - targets: ['api-gateway:80']
  
  - job_name: cadvisor
    scrape_interval: 15s
    static_configs:
      - targets: ['cadvisor:8080']
  
  - job_name: prometheus
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:9090']