global:
  evaluation_interval: 30s
rule_files:
  - /etc/prometheus/prometheus.rules
scrape_configs:

  - job_name: 'sga'
    scrape_interval: 30s
    static_configs:
      - targets: ['sga-service:50053']
      
  - job_name: 'sgm'
    scrape_interval: 30s
    static_configs:
      - targets: ['sgm-service:50054']
  
  - job_name: 'sed'
    scrape_interval: 30s
    static_configs:
      - targets: ['sed-service:50055']
  
  - job_name: cadvisor
    scrape_interval: 30s
    static_configs:
      - targets: ['cadvisor:8080']