apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init
  namespace: weather-sentinel
data:
  init.sql: |
    ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY '1234';
    GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
    FLUSH PRIVILEGES;