apiVersion: apps/v1
kind: Deployment
metadata:
  name: sga-service
  namespace: weather-sentinel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sga-service
  template:
    metadata:
      labels:
        app: sga-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metriche"
    spec:
      containers:
      - name: sga
        image: sga_service_image:latest
        imagePullPolicy: Never
        env:
        # Database
        - name: HOSTNAME
          value: "sga-db"
        - name: PORT
          value: "3306"
        - name: USER
          value: "root"
        - name: PASSWORD_DB
          value: "1234"
        - name: DATABASE_SGA
          valueFrom:
            configMapKeyRef:
              name: sga-config
              key: DATABASE_SGA
              
        # Server
        - name: HOST
          value: "0.0.0.0"
        - name: PORTA_SGA
          value: "5000"  
              
        # SGM
        - name: SGM_HOST 
          value: "sgm-service"
        - name: PORTA_SGM
          value: "80" 
              
        ports:
        - containerPort: 5000
          name: http
        readinessProbe:
          httpGet:
            path: /metriche
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /metriche
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 20
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"