apiVersion: apps/v1
kind: Deployment
metadata:
  name: sga-db
  namespace: weather-sentinel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sga-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sga-db
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: sga-db-password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: sga-config
              key: DATABASE_SGA
        - name: MYSQL_ROOT_HOST
          value: "%"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: sga-db-storage
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command: ["mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
          initialDelaySeconds: 5
          periodSeconds: 2
      volumes:
      - name: sga-db-storage
        persistentVolumeClaim:
          claimName: sga-db-pvc