apiVersion: apps/v1
kind: Deployment
metadata:
  name: sgm-db
  namespace: weather-sentinel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sgm-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sgm-db
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "1234"  # correggere con il secrets
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: sgm-config
              key: DATABASE_SGM
        - name: MYSQL_ROOT_HOST
          value: "%"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: sgm-db-storage
          mountPath: /var/lib/mysql
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping", "-h", "localhost"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command: ["mysqladmin", "ping", "-h", "localhost"]
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: sgm-db-storage
        persistentVolumeClaim:
          claimName: sgm-db-pvc