apiVersion: v1
kind: Service
metadata:
  name: gls-service
  namespace: weather-sentinel
  labels:
    app: gls-service
spec:
  selector:
    app: gls-service
  ports:
  - port: 50056
    targetPort: 50056
    name: grpc
  type: ClusterIP