apiVersion: v1
kind: Service
metadata:
  name: sed-db
  namespace: weather-sentinel
  labels:
    app: sed-db
spec:
  selector:
    app: sed-db
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
  type: ClusterIP