apiVersion: v1
kind: Service
metadata:
  name: sed-service
  namespace: weather-sentinel
  labels:
    app: sed-service
spec:
  selector:
    app: sed-service
  ports:
  - port: 80
    targetPort: 5000
    name: http
  type: ClusterIP