apiVersion: v1
kind: Service
metadata:
  name: sgm-db
  namespace: weather-sentinel
  labels:
    app: sgm-db
spec:
  selector:
    app: sgm-db
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
  type: ClusterIP