apiVersion: v1
kind: Service
metadata:
  name: sgm-service
  namespace: weather-sentinel
  labels:
    app: sgm-service
spec:
  selector:
    app: sgm-service
  ports:
  - port: 80
    targetPort: 5000
    name: http
  type: ClusterIP