apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: weather-sentinel
spec:
  selector:
    app: zookeeper
  ports:
  - port: 2181
    targetPort: 2181
    name: client
  type: ClusterIP